# ByteTrack parameters used for trajectory generation.
tracker_type: bytetrack
track_high_thresh: 0.60
track_low_thresh: 0.1
new_track_thresh: 0.25
track_buffer: 30
match_thresh: 0.8
fuse_score: True
